{% set version = "0.19.1" %}

package:
  name: gitlint-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gitlint-core/gitlint_core-{{ version }}.tar.gz
  sha256: 7bf977b03ff581624a9e03f65ebb8502cc12dfaa3e92d23e8b2b54bbdaa29992

build:
  entry_points:
    - gitlint = gitlint.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - arrow
    - click
    - sh

test:
  imports:
    - gitlint
  commands:
    - pip check
    - gitlint --help
  requires:
    - pip
    - python {{ python_min }}

about:
  dev_url: https://github.com/jorisroovers/gitlint/tree/main/gitlint-core
  home: https://github.com/jorisroovers/gitlint
  license: MIT
  license_file: LICENSE
  summary: Git commit message linter written in python, checks your commit messages for style.

extra:
  recipe-maintainers:
    - danielnachun
